name: home
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  dependencies:
    path: ../../dependencies
  design_system:
    path: ../../design_system
  flutter:
    sdk: flutter
  identity:
    path: ../identity

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter: null
