name: tds_movye_app
description: Base app that contains main class of Movye App.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  core:
    path: packages/core
  dependencies:
    path: packages/dependencies
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  home:
    path: packages/modules/home
  identity:
    path: packages/modules/identity
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/videos/
    - .env
