name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_injector: ^1.0.2+2
  cached_network_image: ^3.2.3
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  form_validator: ^2.1.1
  go_router: ^7.0.2
  google_fonts: ^4.0.4
  intl: ^0.17.0
  pinput: ^2.2.31
  shared_preferences: ^2.1.2
  video_player: ^2.6.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter: null
