name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_injector: ^1.0.2+2
  flutter:
    sdk: flutter
  go_router: ^7.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
